{
  #自己組織化マップの作成関係
  "label_disp": , #表示するラベル. リストで指定する. 全部表示するときは何も書かない
  "input_path" : "test.dat", #自己組織化マップ用の入力ベクトルファイルのパス.
                             #make_som_data(https://github.com/visual-media-lab/make_som_data)により出力される入力ベクトルファイルの形式に準拠すること
  "n_rows": 24, #自己組織化マップの縦方向の行数
  "n_cols": 30, #自己組織化マップの横方向の列数

  #高度なオプション
  "epochs": 10000, #何回学習するか
  "maptype": "toroid", #円環体に描画させる
  
  #結果の出力関係
  "codebook_path": "codebook.pickle", #コードブックを出力するパス. pickle形式で保存される
  "umatrix_path": "umatrix.pickle", #umatrixを保存するパス. pickle形式で保存される. 再描画を行う際はこのファイルを使用する.
  "som_path": "result.png", #出力されたSOMを画像として保存するパス.
}